name: talib_al_jamia
description: طالب الجامعة - إدارة الحياة الجامعية والشقة والمال.
publish_to: none
version: 0.1.0+1

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.3
  provider: ^6.1.2
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
