name: talib_al_jamia
description: My Task - personal university life management.
publish_to: none
version: 0.1.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.3
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  supabase_flutter: 2.17.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  image_path: assets/images/my_task_logo.png
